name = "cf-chatgptelegram"
main = "src/index.ts"
compatibility_date = "2023-02-17"
kv_namespaces = [{ binding = "CHAT_KV", id = "15d53f8eb18644e3b8dbff6714b78787" }]

[vars]

CHAT_LANGUAGE = "Taiwan Chinese"

# SECERT: TG_TOKEN
